apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-cache-daemon
spec:
  template:
    spec:
      containers:
      - name: image-cache-daemon
        args:
          - --warden-image=warden:ci