name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-test-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-test-
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Test
      run: go test -v ./...

  # Always build images just to ensure that they're buildable,
  # but only push them to the registry if this is a push to master
  build-images:
    runs-on: ubuntu-latest
    needs:
      - test
      - lint
      - e2e
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Warden Image
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile.warden
        push: ${{ github.event_name == 'push'}}
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386
        tags: |
          ghcr.io/dcherman/image-cache-daemon-warden:latest
          ghcr.io/dcherman/image-cache-daemon-warden:{{ env.GITHUB_SHA }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Build Image Cache Daemon Image
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile
        push: ${{ github.event_name == 'push'}}
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386
        tags: |
          ghcr.io/dcherman/image-cache-daemon:latest
          ghcr.io/dcherman/image-cache-daemon:{{ env.GITHUB_SHA }}
        cache-from: type=gha
        cache-to: type=gha,mode=max


  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Warden Image
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile.warden
        load: true
        tags: |
          ghcr.io/dcherman/image-cache-daemon-warden:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Build Image Cache Daemon Image
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile
        load: true
        tags: |
          ghcr.io/dcherman/image-cache-daemon:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        only-new-issues: true
        args: --timeout=15m
